#!/bin/bash

export BG_BLACK=$(tput setab 0)
export BG_RED=$(tput setab 1)
export BG_GREEN=$(tput setab 2)
export BG_YELLOW=$(tput setab 3)
export BG_BLUE=$(tput setab 4)
export BG_MAGENTA=$(tput setab 5)
export BG_CYAN=$(tput setab 6)
export BG_WHITE=$(tput setab 7)

export FG_BLACK=$(tput setaf 0)
export FG_RED=$(tput setaf 1)
export FG_GREEN=$(tput setaf 2)
export FG_YELLOW=$(tput setaf 3)
export FG_BLUE=$(tput setaf 4)
export FG_MAGENTA=$(tput setaf 5)
export FG_CYAN=$(tput setaf 6)
export FG_WHITE=$(tput setaf 7)

export BG_RESET=$(tput setab 9)
export FG_RESET=$(tput setaf 9)
export END_SGR=$(tput sgr0)
export END_SGRU=$(tput smul)
export FG_B=$(tput bold)
export FG_U=$(tput smul)

export BIN="$HOME/bin"
export PATH="$BIN:/usr/local/opt/ruby@2.3/bin:/usr/local/opt/openssl/bin:$HOME/.composer/vendor/bin:/usr/local/bin:$PATH"
export PS1="$FG_MAGENTA=>$END_SGR $FG_WHITE\w$END_SGR  $FG_CYAN\$$END_SGR  "
export PROMPT_COMMAND=""

export TERM="xterm-color"
export GREP_OPTIONS='--color=auto' GREP_COLOR='1;32'
export CLICOLOR="1"
export LSCOLORS="ExFxCxDxBxegedabagacad"

export GIT_URL="https://github.com"
export DIR_LOG="$BIN/dir.log"
export subl=`echo "Sublime Text"`
