#!/bin/bash


source "$HOME/bin/_variables"


function git_check() {
  local ps=

  if [[ -e "$PWD/.git" ]]; then
    local branch=`cat "$PWD/.git/HEAD" | perl -pe "s/ref\: refs\/heads\///g"`
    local ps="  < ${branch} ${FG_GREEN}${END_SGR} >"
    local refs=`cat "$PWD/.git/refs/heads/${branch}"`
    local status=`git status -s`

    if [[ -n $status ]]; then
      local ps="  < ${FG_MAGENTA}${branch}${END_SGR} ${FG_YELLOW}${END_SGR}${FG_RED}${END_SGR} >"
    fi
  fi

  export PS1="${FG_MAGENTA}${FG_B}λ${END_SGR}  ${FG_GREEN}\u${END_SGR}  in  ${FG_YELLOW}[\w]${END_SGR}${ps}\n${FG_WHITE}\$${END_SGR}  "
}


function refresh_profile() {
  source "$HOME/.bash_profile"
  source "$HOME/.bashrc"
  source "$HOME/.exrc"
}


export PATH="$BIN:/usr/local/opt/ruby@2.3/bin:/usr/local/opt/openssl/bin:$HOME/.composer/vendor/bin:/usr/local/bin:$PATH"
export PROMPT_COMMAND='git_check && refresh_profile'




export TERM="xterm-color"
export GREP_OPTIONS='--color=auto'
export GREP_COLOR='1;32'
export CLICOLOR="1"
export LSCOLORS="ExFxCxDxBxegedabagacad"
