#!/usr/bin/bash

## Colors
# Background
export BG_DEF="\[\e[39m\]"
export BG_BLACK="\[\e[40m\]"
export BG_RED="\[\e[41m\]"
export BG_GREEN="\[\e[42m\]"
export BG_YELLOW="\[\e[43m\]"
export BG_BLUE="\[\e[44m\]"
export BG_MAGENTA="\[\e[45m\]"
export BG_CYAN="\[\e[46m\]"
export BG_WHITE="\[\e[47m\]"
# Foreground
export FG_DEF="\[\e[39m\]"
export FG_BLACK="\[\e[30m\]"
export FG_RED="\[\e[31m\]"
export FG_GREEN="\[\e[32m\]"
export FG_YELLOW="\[\e[33m\]"
export FG_BLUE="\[\e[34m\]"
export FG_MAGENTA="\[\e[35m\]"
export FG_CYAN="\[\e[36m\]"
export FG_WHITE="\[\e[37m\]"
# Others
export BG_RESET="\[\e[49m\]"
export FG_RESET="\[\e[39m\]"
export END_SGR="\[\e[0m\]"
export END_SGRU="\[\e[0m\]"
export FG_B="\[\e[1m\]"
export FG_D="\[\e[2m\]"
export FG_U="\[\e[4m\]"
export FG_BL="\[\e[5m\]"
export FG_R="\[\e[7m\]"
export FG_H="\[\e[8m\]"


export WWW=$HOME'/www'
export BIN=$HOME'/.bin'
export GIT_URL='git@github.com:'

export PATH=~/.bin:/usr/local/lib/node_modules/yslow/bin:/usr/local/opt/ruby@2.3/bin:/usr/local/opt/openssl/bin:~/.composer/vendor/bin:~/.npm:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin
export PROMPT_COMMAND='git_check && refresh_profile'
export TERM="xterm-color"
export GREP_OPTIONS='--color=auto'
export GREP_COLOR='1;32'
export CLICOLOR="1"
export LSCOLORS="ExFxCxDxBxegedabagacad"
# History: don't store duplicates
export HISTCONTROL=erasedups
# History: 10,000 entries
export HISTSIZE=100


test -e "${HOME}/.iterm2_shell_integration.bash" && source "${HOME}/.iterm2_shell_integration.bash"

## Paths Alias
# --------------------------------------
export rgm=$WWW/repro-gallery-master