#!/bin/bash


## Colors
# Background
export BG_DEF="\[\e[39m\]"
export BG_BLACK="\[\e[40m\]"
export BG_RED="\[\e[41m\]"
export BG_GREEN="\[\e[42m\]"
export BG_YELLOW="\[\e[43m\]"
export BG_BLUE="\[\e[44m\]"
export BG_MAGENTA="\[\e[45m\]"
export BG_CYAN="\[\e[46m\]"
export BG_WHITE="\[\e[47m\]"
# Foreground
export FG_DEF="\[\e[39m\]"
export FG_BLACK="\[\e[30m\]"
export FG_RED="\[\e[31m\]"
export FG_GREEN="\[\e[32m\]"
export FG_YELLOW="\[\e[33m\]"
export FG_BLUE="\[\e[34m\]"
export FG_MAGENTA="\[\e[35m\]"
export FG_CYAN="\[\e[36m\]"
export FG_WHITE="\[\e[37m\]"
# Others
export BG_RESET="\[\e[49m\]"
export FG_RESET="\[\e[39m\]"
export END_SGR="\[\e[0m\]"
export END_SGRU="\[\e[0m\]"
export FG_B="\[\e[1m\]"
export FG_D="\[\e[2m\]"
export FG_U="\[\e[4m\]"
export FG_BL="\[\e[5m\]"
export FG_R="\[\e[7m\]"
export FG_H="\[\e[8m\]"


## Symbols
export SYMBOLS='λ    ⤑    ⤇    ⤵    ⚡    ⚓    ☕    ⨯    ⩐    ⩨    𐄷    𐄹    ˿    ⌘    @    ➾    ⌦    ⌫    ⎈    ⎋    ⏏    ⌗    ⍟    ⍝    ⍣    ⎆    ⌚    ⌛    ⌨    ⏎    ⚙    🜨    🜲    🝙    🝱'


## Additional paths
export BIN="$HOME/bin"
export DIR_LOG="$BIN/dir.log"
export TODO_DIR="$BIN/todo"
export TODOTXT_CFG_FILE="$TODO_DIR/todo.cfg"
export TODO_ACTIONS_DIR="$TODO_DIR/addons"
export MAN="$BIN/manpages"
export HYPER="${HOME}/.hyper_plugins"
export HYPER_LOCAL="${HYPER}/local"


## github
export GIT_URL="git@github.com:"


## Others
# export EDITOR="Atom"




# editors
export EDITOR='Atom Beta'
export GIT_EDITOR='Atom Beta'
export SHELL='/bin/bash'

# modules
export JS_CMD="node"
export NODE_PATH="/usr/local/lib/node_modules"
