#!/bin/bash

alias export=" export"
alias grep="grep --color=auto"
alias egrep="egrep --color=auto"
alias fgrep="fgrep --color=auto"
alias pbcopy=" pbcopy -Prefer txt"
# alias pbcopy=" tr -d '\n' | pbcopy -Prefer txt"
alias ls="ls -lAFh"
alias la="ls -1AFh"
alias lc="ls -CAFh"
alias lf="ls | grep --color=never '^-'"
alias ld="ls | grep --color=never '^d'"
alias h?="history | grep -E -i"
alias ip="dig +short myip.opendns.com @resolver1.opendns.com"
alias localip="ipconfig getifaddr en0"
alias wpkey="curl -G https://api.wordpress.org/secret-key/1.1/salt/ | pbcopy"

alias dotdsclear="find . -type f -name '*.DS_Store' -ls -delete"
alias lsclear="/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -kill -r -domain local -domain system -domain user && killall Finder"
alias emptytrash="sudo rm -rfv /Volumes/*/.Trashes; sudo rm -rfv ~/.Trash; sudo rm -rfv /private/var/log/asl/*.asl; sqlite3 ~/Library/Preferences/com.apple.LaunchServices.QuarantineEventsV* 'delete from LSQuarantineEvent'"
alias urlencode='python -c"import sys, urllib as ul; print ul.quote_plus(sys.argv[1]);"'
# Merge PDF files
# Usage: `mergepdf -o output.pdf input{1,2,3}.pdf`
alias mergepdf='/System/Library/Automator/Combine\ PDF\ Pages.action/Contents/Resources/join.py'
# Print each PATH entry on a separate line
alias path='echo -e ${PATH//:/\\n}'
alias v="command -v"

alias vim="vim ex"
alias clearmail="sudo rm /var/mail/`whoami`"
alias apmclearcache='(cd /Users/sudprawat/.atom && rm -rf blob-store compile-cache storage recovery)'

alias pd='_parent'
alias bd='_home'

alias laravel-create="composer create-project --prefer-dist laravel/laravel"
alias laravel-mod="chmod -R 0775 bootstrap/cache storage database/seeds"

alias gems="gem search"
alias gemi="gem install"
alias geml="gem list"
alias gemun="gem list"

alias npms="npm search"
alias npmi="npm install"
alias npml="npm list"

alias brews="brew search"
alias brewi="brew install"
alias brewl="brew list"
alias brewinfo="brew search --desc"

# alias sugem="sudo gem"
# alias sugems="sugem search"
# alias sugemi="sugem install"
# alias sugeml="sugem list"
