#!/bin/bash


if [ -e /usr/share/terminfo/x/xterm-256color ]; then
  export TERM='xterm-256color';
else
  export TERM='xterm-color';
fi


# export TERM="xterm-256color";
export GREP_OPTIONS="--color=auto";
export GREP_COLOR="1;32";
export CLICOLOR="1";
export LSCOLORS="ExFxCxDxBxegedabagacad";

# Increase Bash history size.
export HISTSIZE="10000";
export HISTFILESIZE="$HISTSIZE";
# Omit duplicates and commands that begin with a space from history.
export HISTCONTROL='erasedups';
# export HISTCONTROL='ignoreboth';
# Set default editor to Atom
export EDITOR="Atom";
# Enable persistent REPL history for `node`.
export NODE_REPL_HISTORY="$HOME/.node_history";
# Allow 32³ entries; the default is 1000.
export NODE_REPL_HISTORY_SIZE="32768";
# Use sloppy mode by default, matching web browsers.
export NODE_REPL_MODE="sloppy";
# Make Python use UTF-8 encoding for output to stdin, stdout, and stderr.
export PYTHONIOENCODING="UTF-8";
# Prefer US English and use UTF-8.
export LANG='en_US.UTF-8';
export LC_ALL='en_US.UTF-8';
# Highlight section titles in manual pages.
export LESS_TERMCAP_md="$yellow";
# Don’t clear the screen after quitting a manual page.
export MANPAGER='less -X';
# Avoid issues with `gpg` as installed via Homebrew.
export GPG_TTY=$(tty);
