#!/usr/bin/env php
<?php
error_reporting(0);

// extract($_SERVER);
$argv = $_SERVER['argv'];
array_shift($argv);

if (!isset($argv[0]) || !$argv[0] || count($argv) != 1) {
    echo "usage: FFFFFF";

    return;
}

$hex = '#' . str_replace('#', '', $argv[0]);

list($r, $g, $b) = sscanf($hex, "#%02x%02x%02x");

shell_exec("echo $r, $g, $b | pbcopy -Prefer txt");
echo "$r, $g, $b";

// extract($_SERVER);
// $r = $argv[1];
// $g = $argv[2];
// $b = $argv[3];

// if ($r < 0 || $g < 0 || $b < 0) {
//     echo "usage: R G B";
//     echo "\n";
// } else {
//     // 30, 37, 31
//     echo ($r + round($r * .30)) . ", " . ($g + round($g * .351)) . ", " . ($b + round($b * .295));
//     echo "\n";
// }

echo "\n";