#!/bin/bash

cmd=$(basename $0)

function usage() {
    echo "usage: $cmd - name"
}

if [[ -z $1 ]]; then
    usage && exit 0
fi

file=$BIN/$1
shift

if [[ ! -e $file ]]; then
    echo "$file not exists"
else
    rm "$file"
    echo "$file removed"
fi

complete 1