#!/bin/bash

set -e

CMD=""
FILE=""

if [[ -z "$1" ]]; then
  echo "Please enter command name."
else
  CMD="$1"; shift
  FILE="$BIN/$CMD"
  ONPATH=""

  if [[ -n $1 ]]; then
    ONPATH="$1"
    shift
    FILE="$BIN/$ONPATH/$CMD"
  fi

  if [[ -e "$FILE" ]]; then
    open -a "Sublime Text" "$FILE"
  else
    echo "Command $FILE not found."
  fi
fi
