#!/bin/bash

USER="nopphasinara"
EMAIL="nopphasin.arayasirikul@gmail.com"
REPO=""

if [[ -z $1 ]]; then
  echo "Please enter git repository."
else
  REPO="$1"
  shift

  git init
  git config user.name "$USER"
  git config user.email "$EMAIL"

  git remote add origin -f "$GIT_URL$REPO"

  git config branch.master.remote origin
  git config branch.master.merge master
fi
