#!/bin/bash

cmd=$(basename $0)

function usage() {
    echo "usage: $cmd - [name]"
}

target=$1
shift

case "${target}" in
    'atom')
        target="${HOME}/.atom"
    ;;
    'bin')
        target="${BIN}"
    ;;
    'rgm')
        target="${HOME}/www/repro-gallery-master"
    ;;
esac

if [[ -z $target ]]; then
    git add .
    git commit -m "Update packages"
    git push $*
else
    ( cd $target && git add . && git commit -m "Update packages" && git push $* )
fi

complete 1