#!/bin/bash


now=`date +%s`
last_commit=`git log --pretty=format:'%at' -1`
seconds=$((now-last_commit))
minutes=$((seconds/60))
hours=$((minutes/60))
days=$((hours/24))

gitinfo=`git_info | perl -pe s/"✗"/""/g`
gitinfo=`echo ${gitinfo} | perl -pe s/' ]'/']'/g`

project_name=$(printf "$(shell_escape ${FG_BLUE}${FG_B}$(basename $PWD)${END_SGR})")

cat <<-EndVersion

/*
|--------------------------------------------------------------------------
| Project ${project_name} [ ${gitinfo} ]
|--------------------------------------------------------------------------
|
| Last Commit - $(timeago $last_commit)
|
*/

EndVersion
