#!/bin/bash


cmd=$(basename $0)

function usage() {
  cat <<-EndVersion
  usage: $cmd command
EndVersion

  complete 1
}


if [[ $# != 1 ]]; then
  usage
else
  called_cmd=$1
  shift

  man $MAN/$called_cmd.html
fi
