#!/bin/bash


cmd=$(basename $0)

function usage() {
  cat <<-EndVersion
  usage: $cmd source target
EndVersion

  complete 1
}


if [[ $# != "2" || -z $1 || -z $2 ]]; then
  usage
else
  sudo ln -s $1 $2
fi
