#!/bin/bash


cmd=`basename $0`

function usage() {
  cat <<-EndVersion
  $FG_B# === $cmd - Mount disk to specified volume ===
  #$END_SGR
  Usage: $cmd disk mount_folder

  First release: DD/MM/YYYY
  Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
  consequat.
EndVersion
  exit 1
}

if [[ -z $1 || -z $2 ]]; then
  usage
else
  disk=$1
  folder=$2
  shift 2

  sudo mount -t ntfs /dev/$disk /Volumes/$folder/
fi

# function usage() {
#   local -r msg="usage: $FG_BLUE$FG_B$cmd$END_SGR disk mount_folder \
#   asd asd asd"
#
#   echo -ne $msg
# }
#
# if [[ -z $1 || -z $2 ]]; then
#   usage
# else
#   echo $0
# fi

# function usage() {
#   echo -ne "usage: $CMD"
# }
#
# if [[ -z $1 || -z $2 ]]; then
#   usage
# else
#   # statements
# fi
# sudo mount -t ntfs /dev/$DISK /Volumes/$FOLDER/
