#!/bin/bash

CMD=""
FILE=""

if [[ -z "$1" ]]; then
  echo "Please enter command name."
else
  CMD="$1"; shift
  FILE="$BIN/$CMD"
  ONPATH=""

  if [[ -n $1 && $1 != "-e" ]]; then
    ONPATH="$1"
    shift
    FILE="$BIN/$ONPATH/$CMD"
  fi

  if [[ -e "$FILE" ]]; then
    echo "Command $FILE already exists."
  else
    echo -e "#!/bin/bash" &> "$FILE"

    chmod 0755 "$FILE"

    if [[ -n "$1" && "-e" == "$1" ]]; then
      edit_cmd "$CMD" "$ONPATH"
    fi
  fi
fi
