#!/bin/bash


cmd=$(basename $0)

function usage() {
  cat <<-EndVersion
usage: $cmd name commands
EndVersion

  complete 1
}


if [[ $# == 0 ]]; then
  usage
else
  name=$1
  shift
  commands=$1
  shift

  echo -ne "alias ${name}='${commands}'\n" 1>> $BIN/_alias
fi
