#!/bin/bash

CMD=""
FILE=""

if [[ -z "$1" ]]; then
  echo "Please enter command name."
else
  CMD="$1"; shift
  FILE="$BIN/$CMD"

  if [[ -e "$FILE" ]]; then
    echo "Command $FILE already exists."
  else
    echo -e "#!/bin/bash" &> "$FILE"

    chmod 0755 "$FILE"

    if [[ -n "$1" && "-e" == "$1" ]]; then
      edit_cmd "$CMD"
    fi
  fi
fi
