#!/bin/bash

set -e

CMD=""
FILE=""

if [[ -z "$1" ]]; then
  echo "Please enter command name."
else
  CMD="$1"; shift
  FILE="$BIN/$CMD"

  if [[ -e "$FILE" ]]; then
    echo "Command $FILE already exists."
  else
    echo -e "#!/bin/sh" &> "$FILE"

    chmod 0755 "$FILE"
  fi
fi
