#!/bin/bash

git clone https://github.com/angular/quickstart.git quickstart
cd quickstart
npm install

xargs rm -rf < non-essential-files.osx.txt
rm src/app/*.spec*.ts
rm non-essential-files.osx.txt

npm start