#!/usr/bin/env php
<?php
require(__DIR__ . '/lib/autoload.php');

function usage() {
  echo "usage: {$cmd} current_amount amount\n";
}

if (!$argv[0] || !$argv[1] || count($argv) > 2) {
  usage();
} else {
  $percentage = ($argv[0] / $argv[1]) * 100;
  echo "{$argv[0]} / {$argv[1]} * 100 = " . number_format($percentage, 3, '.', '') . "% (" . number_format($percentage / 100, 3, '.', '') . ")";
  echo "\n";
}
