#!/bin/bash


cmd=$(basename $0)

function usage() {
  cat <<-EndVersion
  usage: $cmd variable(s)
EndVersion

  complete 1
}


if [[ $# == 0 ]]; then
  usage
else
  for (( i = 0; i <= $#; i++ )); do
    var=$(env | grep ^$1\=)
    if [[ -z $var ]]; then
      complete 1
    else
      printenv $1
    fi

    shift
  done
fi
