#!/bin/bash


cmd=$(basename $0)

function usage() {
  cat <<-EndVersion
  usage: $cmd branch
EndVersion

  complete 1
}


if [[ $# == 0 ]]; then
  usage
else
  branch=$1 && shift
  git push origin $branch $*
fi
