#!/bin/bash


if [[ -z $1 ]]; then
  echo "Please enter git repository."
else
  REMOTE="origin"
  REPO="$1"
  shift

  git remote add "$REMOTE" -f "$GIT_URL$REPO" $*

  git config branch.master.remote origin
  git config branch.master.merge master
fi
