#!/bin/bash


CMD_NAME=`basename $0`

function usage() {
  echo "usage: $CMD_NAME name email"
}

if [[ -z $1 || -z $2 ]]; then
  usage
else
  NAME="$1"
  EMAIL="$2"
  shift 2

  git config --global user.name "$NAME"
  git config --global user.email "$EMAIL"
  git commit --amend --reset-author
fi
