#!/usr/bin/env php
<?php
error_reporting(0);

array_shift($_SERVER['argv']);
$argv = (isset($_SERVER['argv']) && $_SERVER['argv']) ? $_SERVER['argv'] : array();

foreach ($argv as $cmd) {
    if ($cmd) {
        // $cmd = str_replace(array(
        //     '(', ')', "'", '"'
        // ), array(
        //     '\(', '\)', "\'", '\"'
        // ), $cmd);

        // php -r 'echo json_encode("http://www.domain.com");'
        echo "\n";
        // echo "\n$cmd\n";
        if (substr($cmd, -1) != ';') {
            $cmd .= ';';
        }
        if (strtolower(substr($cmd, 0, 5)) == 'echo ') {
            $cmd = substr($cmd, 5);
        }

        // echo "-> ";
        echo shell_exec("php -r 'echo $cmd'");
        echo "\n";
        // $cmd = str_replace(array(
        //     '(', ')', "'", '"'
        // ), array(
        //     '\(', '\)', "\'", '\"'
        // ), $cmd);
        //
        // echo "command: $cmd\n";
        // if (strtolower(substr($cmd, 0, 4)) != 'echo') { $cmd = "echo ${cmd}"; }
        // if (strtolower(substr($cmd, -1)) != ';') { $cmd = "${cmd};"; }
        // echo "\n";
        // echo '=> ' . shell_exec("php -r '${cmd}'");
    }
}


exit("\n");
