#!/usr/bin/env php
<?php
require(__DIR__ . '/lib/autoload.php');

function usage() {
  global $cmd;
  echo "usage: " . $cmd . " horizontal(s)\n";
}

if (!$argv) {
  usage();
} else {
  $result = array();

  for ($i = 0; $i < $argc; $i++) {
    $x = $argv[$i];
    $xx = ($x / 16);
    $y = ($xx * 9);

    $result[] = $x ." ". number_format($y, 0, '', '');
  }

  echo implode("\n", $result);

  // END
  echo "\n";
}
