#!/bin/bash


cmd=$(basename $0)

function usage() {
  cat <<-EndVersion
usage: $cmd message
EndVersion

  complete 1
}

if [[ -z $1 ]]; then
  errmsg='Successful.'
else
  errmsg=$1
  shift
fi

printf "`shell_escape "${FG_GREEN}${errmsg}${END_SGR}"`\n"
