#!/bin/bash

__source=''
__target=''

if [[ 0 = $# ]]; then
  __return "
  command: `basename $0`
  usage: source target
"; exit 1
else
  if [[ -n $1 ]]; then
    __source=$1; shift
  fi

  if [[ ! -e $__source ]]; then
    __return "
  ERROR: ${__source} does not exists
"; exit 1
  fi

  if [[ -n $1 ]]; then
    __target="${1}"; shift
  else
    __target="${PWD}/${__source}"
  fi

  sudo ln -s "${__source}" "${__target}"

  echo "successful"
fi

complete
