#!/usr/bin/env php
<?php

error_reporting(E_ERROR | E_WARNING);

$argv = ($_SERVER['argc'] <= 0) ? array() : $_SERVER['argv'];

$cmd = (function ($path) {
    if (!$path) return;

    $path = pathinfo($path);
    $path = array_slice($path, -1);

    return implode('', $path);
})($argv[0]);

array_shift($argv);



print_r($argv);
