#!/usr/bin/env php
<?php
function time_elapsed_string($datetime, $full = false) {
    $now = new DateTime;
    $ago = new DateTime($datetime);
    $diff = $now->diff($ago);

    // $diff->w = floor($diff->d / 7);
    // $diff->d -= $diff->w * 7;

    $string = array(
        'y' => 'year',
        'm' => 'month',
        // 'w' => 'week',
        'd' => 'day',
        'h' => 'hour',
        'i' => 'minute',
        's' => 'second',
    );
    foreach ($string as $k => &$v) {
        if ($diff->$k) {
            $v = $diff->$k . ' ' . $v . ($diff->$k > 1 ? 's' : '');
        } else {
            unset($string[$k]);
        }
    }

    if (!$full) $string = array_slice($string, 0, 1);
    return $string ? implode(' ', $string) . ' ago' : 'just now';
}

$time = $_SERVER['argv'];
unset($time[0]);
$time = implode(' ', $time);
if ($time) {
  $is_matches = preg_match("/^([0-9]+)$/i", $time);
  if ($is_matches != 1) {
    $time = strtotime($time);
  }
} else {
  $time = time();
}

echo time_elapsed_string(date('Y-m-d H:i:s', $time), true);
