#!/usr/bin/env php
<?php
require(__DIR__ . '/lib/autoload.php');

function usage() {
  global $cmd;
  echo "usage: " . $cmd . " dec(s)";
  echo "
";
}

if (!$argv) {
  usage();
} else {
  $hex = "00000000";
  $result = array();

  for ($i = 0; $i < $argc; $i++) {
    $len = strlen(dechex($argv[$i]));
    $hex = substr($hex, 0, "-". $len) . dechex($argv[$i]);

    $result[] = strtoupper($hex);
  }

  echo implode(" ", $result);
}

// END
echo "\n";


/*#!/bin/bash
function usage() {
  cat <<-EndVersion
  usage: $(basename $0) decimal(s)
EndVersion

  complete 1
}

cmd=$0
argc=$#

if [[ $argc == "0" ]]; then
  usage
else
  result=""
  argv=$*

  for (( i = 1; i <= $argc; i++ )); do
    result+=" `printf '%x\n' $1`"
    shift
  done

  echo $result

  # printf '%x\n' $1
fi
*/
