#!/bin/bash


cmd=$(basename $0)

function usage() {
  cat <<-EndVersion
  usage: $cmd product_id vendor_id
EndVersion

  complete 1
}


if [[ $# != "2" ]]; then
  usage
else
  from="$HOME/Desktop"
  to="/System/Library/Displays/Contents/Resources/Overrides"

  product_id="DisplayProductID-$1"
  shift
  vendor_id="DisplayVendorID-$1"
  shift

  sudo cp "$from/$product_id.plist" "$to/$vendor_id/$product_id"
fi
