#!/bin/bash


cmd=$(basename $0)

function usage() {
  cat <<-EndVersion
usage: $cmd message
EndVersion

  complete 1
}

if [[ -z $1 ]]; then
  usage
else
  errmsg=$1
  shift

  printf "`shell_escape "${FG_YELLOW}${errmsg}${END_SGR}"`\n"
fi
