#!/bin/bash

alias .="cd";
alias ..="cd ../";
alias ...="cd ../../";
alias ls="ls -lAFh ";
alias la="ls -1 ";
alias lf="ls | grep --color=never '^-'"
alias ld="ls | grep --color=never '^d'"
alias h?="history | grep ";
alias c.="clear ";
alias r.="__reload ";
alias cmdv="command -v ";
alias gem="sudo gem ";
alias composer?="composer search ";
alias gem?="gem search ";
alias brew?="brew search ";
alias npm?="npm search ";
alias apm?="apm search ";
alias composeri="composer require ";
alias composergi="composer global require ";
alias gemi="gem install ";
alias brewi="brew install ";
alias brewt="brew tap ";
alias brewci="brew cask install ";
alias npmi="npm install ";
alias apmi="apm install ";
alias composerr="composer remove ";
alias composergr="composer global remove ";
alias gemun="gem uninstall ";
alias brewun="brew uninstall ";
alias npmun="npm uninstall ";
alias apmun="apm uninstall ";
alias rmf="rm -rf"
alias curdate="date +%Y%m%d";
alias curtime="date +%H%M";
alias gs='git status'
alias gss='git status --short'
alias gl='git log'
alias gcp='git add .; git commit -a -m \"update\"; git push'
alias gph='git push'
alias gpl='git pull'
alias copy="tr -d '\n' | pbcopy"
alias cleanup="find . -type f -name '*.DS_Store' -ls -delete"

# Always enable colored `grep` output
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# Get week number
alias week='date +%V'

alias .home="cd $HOME"
alias .atom="cd $HOME/.atom"
alias .dot="cd $HOME/.dotfiles"
alias .www="cd $HOME/www"
alias .proj="cd $HOME/Projects"
