#!bin/bash

# brew install ack
# brew install autoconf
# brew install freetype
# brew install gettext
# brew install icu4c
# brew install jpeg
# brew install libidn2
# brew install libpng
# brew install libsass
# brew install libtool
# brew install libunistring
# brew install libxml2
# brew install node-build
# brew install node@6
# brew install nodeenv
# brew install openssl
# brew install pcre
# brew install php71
# brew install pkg-config
# brew install readline
# brew install rename
# brew install ssh-copy-id
# brew install unixodbc
# brew install watchexec
# brew install watchman
# brew install wget
# brew install wp-cli
