#!/bin/bash

export _farangs="/Users/sudprawat/www/staging.farangmart.co.th"
export _rpgs="/Users/sudprawat/www/reproduction-galleries"
export _rpg="/Users/sudprawat/www/reproduction-gallery"
export _rgm="/Users/sudprawat/www/repro-gallery-master"
export _www="/Users/sudprawat/www"
export _dot="/Users/sudprawat/.dotfiles"
alias gofarangs="cd `echo /Users/sudprawat/www/staging.farangmart.co.th`"alias gorpgs="cd `echo /Users/sudprawat/www/reproduction-galleries`"alias gorpg="cd `echo /Users/sudprawat/www/reproduction-gallery`"alias gorgm="cd `echo /Users/sudprawat/www/repro-gallery-master`"alias gowww="cd `echo /Users/sudprawat/www`"alias godot="cd `echo /Users/sudprawat/.dotfiles`"