#!/bin/bash

# if [ -f "$__CELLAR_PATH/bash-git-prompt/2.6.3/share/gitprompt.sh" ]; then
#   __GIT_PROMPT_DIR="$__CELLAR_PATH/bash-git-prompt/2.6.3/share";
#   source "$__CELLAR_PATH/bash-git-prompt/2.6.3/share/gitprompt.sh";
# fi

git_status="";
git_branch="";

git_branch() {
  git_status="";
  git_branch="";

  git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/';

  if [[ `git status --porcelain --ignore-submodules=dirty --untracked-files=no 2> /dev/null | tail -n1` ]]; then
    git_status+="untracked-files";
  fi

  git status --porcelain --ignore-submodules=dirty --untracked-files=no 2> /dev/null | tail -n1;

  echo "${git_status}";
}

PS1="\u \h [\w] \$(git_branch) ${git_status}";
PS1+="\n";
PS1+="$ ";
PS2="->";

export PS1;
export PS2;
