#!/bin/bash

is_dirty=''
branch=''
status=''
user="\u"
host=" at \h"
dir=" in [\w]"
ps1="$ "
ps2="-> "

prompt() {
  local ref index
  local flags='--porcelain --ignore-submodules=dirty --untracked-files=no'

  is_dirty=''
  branch=''
  status=''

  ref="$(git symbolic-ref HEAD 2> /dev/null)"
  if [[ $? != 0 ]]; then
    ref="$(git rev-parse --short HEAD 2> /dev/null)"
    if [[ $? != 0 ]]; then
      ref='';
    fi
  fi

  branch="$(echo $ref | grep -e [^\/]*$ -io)"

  if [[ -n `git status ${FLAGS} 2> /dev/null | tail -n1` ]]; then
    is_dirty=1
  fi

  index="$(git status --short --porcelain -b 2> /dev/null)"
  if [[ `echo "$index" | grep -E '^\?\? '` ]]; then
    status+='??'
  fi
  if [[ `echo "$index" | grep '^A  '` ]]; then
    status+='A '
  elif [[ `echo "$index" | grep '^M  '` ]]; then
    status+='A '
  fi
  if [[ `echo "$index" | grep '^ M '` ]]; then
    status+=' M'
  elif [[ `echo "$index" | grep '^AM '` ]]; then
    status+='AM'
  elif [[ `echo "$index" | grep '^ T '` ]]; then
    status+=' T'
  fi
  if [[ `echo "$index" | grep '^R  '` ]]; then
    status+='R '
  fi
  if [[ `echo "$index" | grep '^ D '` ]]; then
    status+=' D'
  elif [[ `echo "$index" | grep '^D  '` ]]; then
    status+='D '
  elif [[ `echo "$index" | grep '^AD '` ]]; then
    status+='AD'
  fi

  prompt_update;
}

prompt_update() {
  PS1="${user}${host}${dir}${is_dirty}${branch}${status}";
  PS1+="\n";
  PS1+="${ps1}";
  export PS1;

  PS2="${ps2}";
  export PS2;
}

export PROMPT_COMMAND="history -a; prompt";
