## Background
export ONDEF="\e[39m"
export ONBLACK="\e[40m"
export ONRED="\e[41m"
export ONGREEN="\e[42m"
export ONYELLOW="\e[43m"
export ONBLUE="\e[44m"
export ONMAGENTA="\e[45m"
export ONPURPLE=$ONMAGENTA
export ONCYAN="\e[46m"
export ONWHITE="\e[47m"

## Foreground
export DEF="\e[39m"
export BLACK="\e[30m"
export RED="\e[31m"
export GREEN="\e[32m"
export YELLOW="\e[33m"
export BLUE="\e[34m"
export MAGENTA="\e[35m"
export PURPLE=$MAGENTA
export CYAN="\e[36m"
export WHITE="\e[37m"

## Others
export BGR="\e[49m"
export FGR="\e[39m"
export R="\e[0m"
export B="\e[1m"
export D="\e[2m"
export U="\e[4m"
export BL="\e[5m"
export REV="\e[7m"
export H="\e[8m"
