#!/bin/bash

home=''
business=''

if [ -f "/Library/Preferences/Parallels/HomeEdition" ]; then
	home=' (ACTIVE)'
else
	business=' (ACTIVE)'
fi

echo 'Choose your version (enter 0, 1 or 2):'
echo 'Выберите версию (введите 0, 1 или 2):'
echo '0. Exit / Выход'
echo "1. Parallels Desktop - Business Edition${business}"
echo "2. Parallels Desktop - Home Edition${home}"

read ver

if [ "$ver" == "1" ]; then
	echo 'Activating Business version...'
	sudo mkdir -p /Library/Preferences/Parallels
	sudo rm -f /Library/Preferences/Parallels/HomeEdition
elif [ "$ver" == "2" ]; then
	echo 'Activating Home Edition...'
	sudo mkdir -p /Library/Preferences/Parallels
	sudo touch /Library/Preferences/Parallels/HomeEdition
elif [ "$ver" != "0" ]; then
	echo 'Invalid input'
	echo 'Некорректный ввод'
fi

echo 'Complete'
echo 'Мы закончили'
